### ISSUE TITLE
Compatibility with Ember 2.0

### ISSUE THREAD

**Issue by repli2dev** [satchmorun/ember-shortcuts#6]
I am trying to use it with Ember 2.0 but I am getting error of missing `foreach` in the line `  var forEach = Ember.EnumerableUtils.forEach;`

**Comment by jhass** [comment]
Would be really great to have Ember 2.0 compatibility.

**Comment by satchmorun** [comment]
Apologies for taking so long with this. The dependency on `Ember.EnumerableUtils` is now gone.
